default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dionysos-lapp_development

test:
  <<: *default
  database: dionysos-lapp_test

production:
  <<: *default
  url: <%= ENV['POSTGRESQL_ADDON_URI'] %>
